## My First Numpy Code Exercises

In [7]:
import numpy as np

## Create a numpy 1D = vector

In [8]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
# 5 equal spaces between 10 and 100
b = np.linspace(10, 100, 5)
b

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [15]:
# Start, end, incriment
a = np.arange(-5, 5, 0.5)
a

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [17]:
# Random numbers between 0 and 1
b = np.random.rand(100)
b

array([0.43956058, 0.06702381, 0.02819331, 0.06912545, 0.20452134,
       0.69892945, 0.5301623 , 0.56557629, 0.73184734, 0.56878243,
       0.9323453 , 0.06266788, 0.19757929, 0.27068212, 0.67829608,
       0.14083402, 0.7533242 , 0.64899192, 0.31215024, 0.67686146,
       0.31540789, 0.72249268, 0.70789645, 0.99821249, 0.24866189,
       0.80324694, 0.4262146 , 0.86121819, 0.21719929, 0.39156147,
       0.22083883, 0.3423345 , 0.932256  , 0.843585  , 0.64467456,
       0.512358  , 0.00266707, 0.1983986 , 0.42219026, 0.55988152,
       0.84825206, 0.28838884, 0.47115001, 0.6294991 , 0.06833867,
       0.22140435, 0.62943668, 0.89369581, 0.76093301, 0.6326543 ,
       0.17002757, 0.51506584, 0.19617235, 0.99370011, 0.15401818,
       0.88727298, 0.79676645, 0.65972696, 0.63105032, 0.36983225,
       0.8545661 , 0.12624215, 0.62113206, 0.32625675, 0.77007624,
       0.32852321, 0.60925435, 0.09174433, 0.43018804, 0.17576519,
       0.6574832 , 0.26099594, 0.64244409, 0.43468722, 0.05587

In [20]:
# Mean variance and std
b.mean(), b.var(), b.std()

(0.4508615524897516, 0.07406494290226413, 0.2721487514251427)

In [21]:
# Column vector
acol = np.array([[1],[2],[3]])
acol

array([[1],
       [2],
       [3]])

In [22]:
# Transpose
acol.T

array([[1, 2, 3]])

## Creating Multi-D Arrays (Matrices)

In [23]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Matrix generation
A = np.arange(100).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
A.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [30]:
# Creates single list from matrix
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
# Will try to combine the two matricies
ix, iy = (4,2)
x = np.linspace(0,1,ix)
y = np.linspace(0,1,iy)
(xv, yv) = np.meshgrid(x,y)
xv, yv

(array([[0.        , 0.33333333, 0.66666667, 1.        ],
        [0.        , 0.33333333, 0.66666667, 1.        ]]),
 array([[0., 0., 0., 0.],
        [1., 1., 1., 1.]]))

In [35]:
A = np.arange(64).reshape(8,8)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [36]:
np.diagonal(A)

array([ 0,  9, 18, 27, 36, 45, 54, 63])

In [38]:
# k lets you get the specific diagonal you want
np.diag(np.diagonal(A), k=1)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 18,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 27,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 36,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 45,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 54,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 63],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [41]:
x = np.arange(10)
y=x
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[0] = 10

In [43]:
x
y=x

In [44]:
y[0]

10

In [45]:
y = np.copy(x)
y

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

## Slicing 1D and 2D Arrays

In [46]:
# Slicing 1D arrays
a = np.arange(100)
a[5:35]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [47]:
# Slicing 2D arrays
A = np.arange(64).reshape(8,8)
A[1:,5:]

array([[13, 14, 15],
       [21, 22, 23],
       [29, 30, 31],
       [37, 38, 39],
       [45, 46, 47],
       [53, 54, 55],
       [61, 62, 63]])

In [48]:
A[1:,5:]=0
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12,  0,  0,  0],
       [16, 17, 18, 19, 20,  0,  0,  0],
       [24, 25, 26, 27, 28,  0,  0,  0],
       [32, 33, 34, 35, 36,  0,  0,  0],
       [40, 41, 42, 43, 44,  0,  0,  0],
       [48, 49, 50, 51, 52,  0,  0,  0],
       [56, 57, 58, 59, 60,  0,  0,  0]])

In [49]:
A = np.arange(64).reshape(8,8)

In [52]:
B = np.triu(A) # Use tril for lowwer triangle

In [54]:
B.size, B.shape, B.ndim

(64, (8, 8), 2)

## Array Operations

In [59]:
a = np.arange(10).reshape(10,1)
b = np.arange(5).reshape(5,1)

In [60]:
a*2

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [62]:
a + b.T

array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [64]:
A = np.random.randn(25).reshape(5,5)
B = np.random.randn(25).reshape(5,5)
A, B

(array([[ 1.0415713 , -1.81463606,  0.79992725, -1.31769595, -0.42635198],
        [ 1.04773316, -0.35404883, -0.07697474,  0.65443782, -1.9263714 ],
        [ 0.33580979,  0.66974606, -1.77010429,  1.94907949,  0.76876757],
        [-2.77793625,  0.69261768,  0.25347017, -0.95935894, -0.85352402],
        [ 0.62798029, -0.73022108,  0.48169826,  0.29324504, -1.73303142]]),
 array([[ 1.65350001, -0.38942879, -1.26493532,  0.77875824, -1.80992064],
        [ 0.58592157,  0.26872262, -0.47620788,  1.71449936,  0.48211903],
        [-1.48417649, -0.64478348,  0.90795778,  0.20422442, -0.51729519],
        [ 0.93975615,  1.87617679, -1.49460662, -1.54029495, -0.38707608],
        [ 0.69330753,  0.30969041,  0.46511445, -0.93990583, -1.24887553]]))

In [65]:
A + B

array([[ 2.69507131, -2.20406485, -0.46500807, -0.53893771, -2.23627262],
       [ 1.63365473, -0.0853262 , -0.55318262,  2.36893718, -1.44425237],
       [-1.14836671,  0.02496258, -0.86214651,  2.15330391,  0.25147238],
       [-1.8381801 ,  2.56879447, -1.24113645, -2.49965389, -1.2406001 ],
       [ 1.32128782, -0.42053067,  0.9468127 , -0.64666079, -2.98190696]])

In [66]:
np.dot(A, B)

array([[-2.06213539, -4.01329917,  2.04405846,  0.29367568, -2.13132134],
       [ 0.9186702 ,  0.17773595, -3.10071391,  0.99577465,  0.125292  ],
       [ 5.93947912,  5.08543357, -4.90643817, -2.67643111, -1.08376238],
       [-6.05701054, -0.95975816,  4.45109776,  1.35584454,  6.66793958],
       [-1.03035701, -0.73789529, -1.25359966,  0.51265828,  0.31300425]])

In [67]:
a = np.random.randn(25)
b = np.random.randn(25)
np.dot(a, b)

-9.350951064691678

In [69]:
C=A*B
C.size

25

In [70]:
A = np.arange(100).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
np.hsplit(A,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]), array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [72]:
np.vsplit(A, 5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [74]:
a = np.array([0,1,0])
b = np.tile(a,100)
b

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [75]:
A = np.arange(36).reshape(6,6)
B = np.tile(A, 5)
B

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,
         4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11,  6,  7,  8,  9,
        10, 11,  6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17, 12, 13, 14, 15,
        16, 17, 12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23, 18, 19, 20, 21,
        22, 23, 18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 24, 25, 26, 27, 28, 29, 24, 25, 26, 27,
        28, 29, 24, 25, 26, 27, 28, 29, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 30, 31, 32, 33, 34, 35, 30, 31, 32, 33,
        34, 35, 30, 31, 32, 33, 34, 35, 30, 31, 32, 33, 34, 35]])

In [76]:
B.size

180

In [78]:
B.shape

(6, 30)

In [83]:
A = np.random.randn(9).reshape(3,3)
A

array([[-0.66697757, -1.0076186 ,  1.25908181],
       [ 0.03491892,  0.07130698, -0.62381152],
       [-1.22828408, -0.10167363,  0.75428973]])

In [84]:
A.sort()
A

array([[-1.0076186 , -0.66697757,  1.25908181],
       [-0.62381152,  0.03491892,  0.07130698],
       [-1.22828408, -0.10167363,  0.75428973]])

In [87]:
B = np.random.randn(16).reshape(4,4)
np.sort(B, axis=0)

array([[-2.12165669, -2.08908863, -1.64726231, -2.61605532],
       [-1.24428074, -1.06564559, -1.27873326, -0.59439398],
       [-0.9830453 , -0.4853717 ,  0.03731798, -0.02804773],
       [-0.60543268, -0.17732203,  0.68050101,  0.27308558]])

In [89]:
b = np.random.randn(16)
np.sort(b)[-5:]

array([0.46128255, 0.51650574, 0.53308729, 1.16064748, 1.43513182])

In [92]:
np.max(b), np.min(b)

(1.4351318191822642, -1.4362952767193595)

In [103]:
# Write a python program to find the most frequent value in a rondomly
# generated array with 30 elements
a = np.random.randint(0, 20, 30)
np.bincount(a).argmax()

19

In [106]:
# x + 2y + z = 2, 2x + 6y + z = 7, x + y + 4z = 3. Solve for x, y and z
A = np.array([[1,2,1],[2,6,1],[1,1,4]])
B = np.array([2,7,3])
result = np.linalg.solve(A,B)
result

array([-3.,  2.,  1.])

In [107]:
# Checking the result and you should get B back
np.dot(A, result)

array([2., 7., 3.])

In [108]:
np.allclose(np.dot(A, result),B)

True

In [114]:
# Boolean indexing
A = np.random.randn(25).reshape(5,5)
A

array([[-0.91613708, -0.69153902,  0.67060158, -1.02751055, -1.22703993],
       [-0.30953076,  0.10194863,  1.70996919, -0.66076206,  1.53590572],
       [ 0.83725925, -1.9014196 ,  1.88062782,  0.46471274, -0.66260975],
       [ 1.15189036,  0.42980613, -0.4486655 ,  0.36804149, -0.28848068],
       [-0.74284605, -0.50387111, -0.07908892,  0.40055888, -1.70996133]])

In [115]:
A[A-A.mean()>0]

array([0.67060158, 0.10194863, 1.70996919, 1.53590572, 0.83725925,
       1.88062782, 0.46471274, 1.15189036, 0.42980613, 0.36804149,
       0.40055888])

In [116]:
# Write a numpy program to find the closest value in an array to a randomly generated scalar value
A = np.array([3,4,55,36,77,88,34,26,59,67])
B = np.random.randint(100)
B

94

In [120]:
index = np.abs(A-B).argmin()
A[index]

88

In [121]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [128]:
# Write a python program to add the $ sign to every element in an array
# Use of universal funcs = decorator functions
@np.vectorize
def add_dollar(arr):
    dollar='$'
    newarr = dollar + str(arr)
    return newarr

In [129]:
a = np.arange(10)
add_dollar(a)

array(['$0', '$1', '$2', '$3', '$4', '$5', '$6', '$7', '$8', '$9'],
      dtype='<U2')